# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='', max_length=255, verbose_name='\u0418\u0441\u0445\u043e\u0434\u043d\u044b\u0439 \u0444\u0430\u0439\u043b')),
                ('language', models.CharField(choices=[('en', '\u0410\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u0438\u0439'), ('ru', '\u0420\u0443\u0441\u0441\u043a\u0438\u0439'), ('ch', '\u041a\u0438\u0442\u0430\u0439\u0441\u043a\u0438\u0439')], default='en', max_length=24, verbose_name='\u042f\u0437\u044b\u043a')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='series.Episode', verbose_name='\u0421\u0435\u0440\u0438\u0430\u043b')),
            ],
            options={
                'verbose_name': '\u0421\u0443\u0431\u0442\u0438\u0442\u0440',
                'verbose_name_plural': '\u0421\u0443\u0431\u0442\u0438\u0442\u0440\u044b',
            },
        ),
    ]
